-- MySQL Script generated by MySQL Workbench
-- Wed Oct 20 09:23:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema senasoft_desarrollo_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema senasoft_desarrollo_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `senasoft_desarrollo_web` DEFAULT CHARACTER SET utf8 ;
USE `senasoft_desarrollo_web` ;

-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `identification` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `state` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `identificacion_UNIQUE` (`identification` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`cards` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(150) NOT NULL,
  `rol` ENUM('Programadores', 'Modulo', 'Tipo de Error') NOT NULL,
  `state` ENUM('Activo', 'Inactivo') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`games` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(5) NOT NULL,
  `programmer_id` INT UNSIGNED NOT NULL,
  `modulo_id` INT UNSIGNED NOT NULL,
  `type_error_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idPartida_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Partida_Cartas_idx` (`programmer_id` ASC) VISIBLE,
  INDEX `fk_Partida_Cartas1_idx` (`modulo_id` ASC) VISIBLE,
  INDEX `fk_Partida_Cartas2_idx` (`type_error_id` ASC) VISIBLE,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Partida_Cartas`
    FOREIGN KEY (`programmer_id`)
    REFERENCES `senasoft_desarrollo_web`.`cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Cartas1`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `senasoft_desarrollo_web`.`cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Cartas2`
    FOREIGN KEY (`type_error_id`)
    REFERENCES `senasoft_desarrollo_web`.`cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`players` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` ENUM('Administrador', 'Invitado') NOT NULL,
  `games_id` INT UNSIGNED NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `order` ENUM('1', '2', '3', '4') NOT NULL,
  `state` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_players_games1_idx` (`games_id` ASC) VISIBLE,
  INDEX `fk_players_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_players_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `senasoft_desarrollo_web`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `senasoft_desarrollo_web`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`decks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`decks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `players_id` INT UNSIGNED NOT NULL,
  `cards_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_decks_players1_idx` (`players_id` ASC) VISIBLE,
  INDEX `fk_decks_cards1_idx` (`cards_id` ASC) VISIBLE,
  CONSTRAINT `fk_decks_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `senasoft_desarrollo_web`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_decks_cards1`
    FOREIGN KEY (`cards_id`)
    REFERENCES `senasoft_desarrollo_web`.`cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`notes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cards_id` INT UNSIGNED NOT NULL,
  `players_id` INT UNSIGNED NOT NULL,
  `observations` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notes_cards1_idx` (`cards_id` ASC) VISIBLE,
  INDEX `fk_notes_players1_idx` (`players_id` ASC) VISIBLE,
  CONSTRAINT `fk_notes_cards1`
    FOREIGN KEY (`cards_id`)
    REFERENCES `senasoft_desarrollo_web`.`cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notes_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `senasoft_desarrollo_web`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
