-- MySQL Script generated by MySQL Workbench
-- Wed Oct 20 08:42:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema senasoft_desarrollo_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema senasoft_desarrollo_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `senasoft_desarrollo_web` DEFAULT CHARACTER SET utf8 ;
USE `senasoft_desarrollo_web` ;

-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `identificacion` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`carta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`carta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(150) NOT NULL,
  `rol` ENUM('Programadores', 'Modulo', 'Tipo de Error') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`partida` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(5) NOT NULL,
  `programador_id` INT UNSIGNED NOT NULL,
  `modulo_id` INT UNSIGNED NOT NULL,
  `tipo_error_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idPartida_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Partida_Cartas_idx` (`programador_id` ASC) VISIBLE,
  INDEX `fk_Partida_Cartas1_idx` (`modulo_id` ASC) VISIBLE,
  INDEX `fk_Partida_Cartas2_idx` (`tipo_error_id` ASC) VISIBLE,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Partida_Cartas`
    FOREIGN KEY (`programador_id`)
    REFERENCES `senasoft_desarrollo_web`.`carta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Cartas1`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `senasoft_desarrollo_web`.`carta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Cartas2`
    FOREIGN KEY (`tipo_error_id`)
    REFERENCES `senasoft_desarrollo_web`.`carta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`jugador` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rol` ENUM('Administrador', 'Invitado') NOT NULL,
  `partida_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `orden` ENUM('1', '2', '3', '4') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  INDEX `fk_Jugadores_Partida1_idx` (`partida_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_jugador_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Jugadores_Partida1`
    FOREIGN KEY (`partida_id`)
    REFERENCES `senasoft_desarrollo_web`.`partida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `senasoft_desarrollo_web`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`baraja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`baraja` (
  `idBarajas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `carta_id` INT UNSIGNED NOT NULL,
  `jugador_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBarajas`),
  INDEX `fk_Barajas_Cartas1_idx` (`carta_id` ASC) VISIBLE,
  INDEX `fk_baraja_jugador1_idx` (`jugador_id` ASC) VISIBLE,
  CONSTRAINT `fk_Barajas_Cartas1`
    FOREIGN KEY (`carta_id`)
    REFERENCES `senasoft_desarrollo_web`.`carta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_baraja_jugador1`
    FOREIGN KEY (`jugador_id`)
    REFERENCES `senasoft_desarrollo_web`.`jugador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_desarrollo_web`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_desarrollo_web`.`nota` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `carta_id` INT UNSIGNED NOT NULL,
  `jugador_id` INT UNSIGNED NOT NULL,
  `observaciones` TEXT NOT NULL,
  INDEX `fk_Notas_Cartas1_idx` (`carta_id` ASC) VISIBLE,
  INDEX `fk_notas_jugador1_idx` (`jugador_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Notas_Cartas1`
    FOREIGN KEY (`carta_id`)
    REFERENCES `senasoft_desarrollo_web`.`carta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_jugador1`
    FOREIGN KEY (`jugador_id`)
    REFERENCES `senasoft_desarrollo_web`.`jugador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
